name: Spires
favicon: null
layout_spectrum: 0.39733
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#33383b'
    - '#afb3b6'
    - '#2ca593'
    - '#2ad8af'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
