name: Spires
favicon: null
layout_spectrum: 0.49689
typography_spectrum: 0.90566
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#33383b'
    - '#afb3b6'
    - '#2ca593'
    - '#2ad8af'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
