name: Spires
favicon: null
layout_spectrum: 0.24475
typography_spectrum: 0.7377404845319688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#33383b'
    - '#afb3b6'
    - '#2ca593'
    - '#2ad8af'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
