name: Spires
favicon: null
layout_spectrum: 0.049206273863092065
typography_spectrum: 0.7377404845319688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00ffd6'
    - '#ffffff'
    - '#4fffe3'
    - '#dbfff9'
    - '#83ffeb'
  brandStrength: 0.8125
  lightness: 0.479333755094558
  saturation: 0.6194047196768224
  rhythmicContrast: 0.7909126342274249
purpose: []
